name: Java CI

on: [push, pull_request]

jobs:
  test:
    name: Package and run all tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Maven Package
      run: mvn package --batch-mode --show-version --activate-profiles travis

